version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 5s
      retries: 5

  productservice:
    build:
      context: ../
      dockerfile: services/productservice/Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ../services/productservice/.env
    depends_on:
      postgres:
        condition: service_healthy

  productseeder:
    build:
      context: ../
      dockerfile: services/productservice/Dockerfile.seed
    env_file:
      - ../services/productservice/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: "on-failure"

  userservice:
    build:
      context: ../
      dockerfile: services/userservice/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ../services/userservice/.env
    depends_on:
      postgres:
        condition: service_healthy

  userseeder:
    build:
      context: ../
      dockerfile: services/userservice/Dockerfile.seed
    env_file:
      - ../services/userservice/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: "on-failure"

  orderservice:
    build:
      context: ../
      dockerfile: services/orderservice/Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ../services/orderservice/.env
    depends_on:
      postgres:
        condition: service_healthy

  cartservice:
    build:
      context: ../
      dockerfile: services/cartservice/Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - ../services/cartservice/.env
    depends_on:
      postgres:
        condition: service_healthy
      orderservice:
        condition: service_started

  searchservice:
    build:
      context: ../
      dockerfile: services/searchservice/Dockerfile
    ports:
      - "8084:8084"
    env_file:
      - ../services/searchservice/.env
    environment:
      - DATABASE_DSN=host=postgres user=root password=secret dbname=ecommerce port=5432 sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
      orderservice:
        condition: service_started
